export const cuisineList = [
    "American",
    "BBQ", 
    "Italian",
    "Mexican",
    "Greek",
    "Chinese",
    "Thai", 
    "Japanese",
    "Spanish", 
    "French",
    "California",
    "Nordic",
    "Farm-to-Table",
    "Vegetarian and Vegan",
    "Korean BBQ",
    "Modern Australian",
    "New Orleans Creole",
    "Peruvian Nikkei",
    "Middle Eastern Mezze"
]